import pino from 'pino';

const isDevelopment = process.env.NODE_ENV === 'development';
const logLevel = process.env.LOG_LEVEL || 'info';

export const logger = pino({
  level: logLevel,
  redact: {
    paths: [
      'req.headers.authorization',
      'req.headers.cookie',
      'headers.authorization',
      'headers.cookie',
      'authorization',
      'cookie',
      'accessToken',
      'refreshToken',
      'token',
      'password',
      'resetToken',
      'verificationToken',
      'emailVerificationToken',
      'emailChangeToken',
      'deletionToken',
      'downloadToken',
      'cancelToken',
      'cancelTokenHash',
      'tokenHash',
      'inviteToken',
      'inviteUrl',
      'rawInviteUrl',
      'verificationUrl',
      'emailChangeUrl',
      'deletionCancelUrl',
      'downloadUrl',
      'uploadUrl',
      'uploadUrls',
      'mediaUrl',
      'mediaUrls',
      'manifestUrl',
      'segmentUrl',
      'fallbackUrl',
      'posterUrl',
      'hlsManifestUrl',
      'hlsSegmentUrl',
      'storageKey',
      'storageKeys',
      'objectKey',
      'objectKeys',
      'localPath',
      'localPaths',
      'fallbackPath',
      'posterPath',
      'hlsPlaylistPath',
      'hlsSegments',
      'path',
      'subscription.endpoint',
      'pushEndpoint',
      'endpoint',
      'mobilePushToken',
      'pushToken',
      'deviceToken',
      'providerReceipt',
      'providerReceipts',
      'verificationChallenge',
      'challenge',
      'challengeHash',
      'installationId',
      'installationHash',
      'deviceId',
      'body',
      'message.body',
      'message.text',
      'caption',
      'comment.body',
      'commentBody',
      'reportEvidence',
      'evidence',
      'sourceText',
      'privateActionData',
      'aiData',
      'messageBody',
      'prompt',
      'context',
      'sessionToken',
      'eventToken',
      'candidateToken',
      'candidateTokens',
      'playbackToken',
      'playbackSessionToken',
      'score',
      'scores',
      'affinity',
      'affinityScore',
      'candidateIds',
      'candidateList',
      'ranking',
      'rankingInternals',
    ],
    censor: '[redacted]',
  },
  transport: isDevelopment
    ? {
        target: 'pino-pretty',
        options: {
          colorize: true,
          translateTime: 'HH:MM:ss Z',
          ignore: 'pid,hostname',
        },
      }
    : undefined,
  formatters: {
    level: (label) => {
      return { level: label };
    },
  },
  timestamp: pino.stdTimeFunctions.isoTime,
});

export default logger;
